In [1]:
import numpy as np

In [2]:
np.linspace(0, 5, 8)

array([0.        , 0.71428571, 1.42857143, 2.14285714, 2.85714286,
       3.57142857, 4.28571429, 5.        ])

In [4]:
np.random.rand(3,2)


array([[0.07579548, 0.42521042],
       [0.45717767, 0.37985227],
       [0.54477431, 0.39126647]])

In [5]:
arr = np.array([[1,2], [3,4],[5,6]], dtype=np.complex64)

In [6]:
arr

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]], dtype=complex64)

In [8]:
np.zeros_like(arr)

array([[0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j]], dtype=complex64)

In [13]:
arr= np.empty((2,3))

In [20]:
arr

array([[0.07579548, 0.42521042, 1.        ],
       [0.37985227, 0.54477431, 0.39126647]])

In [19]:
arr[0:1,2] = 1

In [21]:
arr = [[0, 1, 2], [3, 4, 5]]


In [22]:
arr

[[0, 1, 2], [3, 4, 5]]